# Generated by Django 3.1.5 on 2022-04-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220331_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='Anon', max_length=50),
        ),
    ]
